// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnirdzofjcwzojabzmxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuaXJkem9mamN3em9qYWJ6bXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNzM2NTksImV4cCI6MjA1Nzg0OTY1OX0.Xdi_dqb50VqGolo-Cbb0Ph358EHoewusJS3R30P_DUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);